export const mockProperties = [
    // ======================
    // Residential
    // ======================
    {
        slug: "dharmawangsa",
        title: "Dharmawangsa",
        priceStart: 6000000000,
        promo: "Info Lengkap",
        category: "Residential",
        bedrooms: 5,
        bathrooms: 3,
        location: "BSD City, Tangerang",
        status_sale: "For Sale",
    },
    {
        slug: "nivara",
        title: "Nivara",
        priceStart: 5900000000,
        promo: "Info Lengkap",
        category: "Residential",
        bedrooms: 5,
        bathrooms: 3,
        location: "BSD City, Tangerang",
        status_sale: "For Sale",
    },
    {
        slug: "azzura",
        title: "Azzura",
        priceStart: 5000000000,
        promo: "Promo Free PPN",
        category: "Residential",
        bedrooms: 4,
        bathrooms: 3,
        location: "BSD City, Tangerang",
        status_sale: "For Sale",
    },
    {
        slug: "botanica-adila",
        title: "Botanica Adila",
        priceStart: 4000000000,
        promo: "Promo Free PPN",
        category: "Residential",
        bedrooms: 4,
        bathrooms: 2,
        location: "BSD City, Tangerang",
        status_sale: "For Sale",
    },
    {
        slug: "botanica-bellis",
        title: "Botanica Bellis",
        priceStart: 2900000000,
        promo: "Promo Free PPN",
        category: "Residential",
        bedrooms: 3,
        bathrooms: 2,
        location: "BSD City, Tangerang",
        status_sale: "For Sale",
    },
    {
        slug: "riviera",
        title: "Riviera",
        priceStart: 1700000000,
        promo: "Promo Free PPN",
        category: "Residential",
        bedrooms: 3,
        bathrooms: 2,
        location: "BSD City, Tangerang",
        status_sale: "For Sale",
    },
    {
        slug: "vista",
        title: "Vista",
        priceStart: 3000000000,
        promo: "Promo Free PPN",
        category: "Residential",
        bedrooms: 4,
        bathrooms: 2,
        location: "BSD City, Tangerang",
        status_sale: "For Sale",
    },
    {
        slug: "wichita",
        title: "Wichita",
        priceStart: 1500000000,
        promo: "Info Lengkap",
        category: "Residential",
        bedrooms: 3,
        bathrooms: 2,
        location: "BSD City, Tangerang",
        status_sale: "For Sale",
    },
    {
        slug: "nordic",
        title: "Nordic",
        priceStart: 2000000000,
        promo: "Info Lengkap",
        category: "Residential",
        bedrooms: 3,
        bathrooms: 2,
        location: "BSD City, Tangerang",
        status_sale: "For Sale",
    },

    // ======================
    // Commercial
    // ======================
    {
        slug: "emerald-core",
        title: "Emerald Core",
        priceStart: 8000000000,
        promo: "Promo Free PPN",
        category: "Commercial",
        bedrooms: 0,
        bathrooms: 4,
        location: "BSD City, Tangerang",
        status_sale: "For Rent",
    },
    {
        slug: "botanica-avenue-2",
        title: "Botanica Avenue 2",
        priceStart: 4000000000,
        promo: "Promo Free PPN",
        category: "Commercial",
        bedrooms: 0,
        bathrooms: 2,
        location: "BSD City, Tangerang",
        status_sale: "For Rent",
    },
    {
        slug: "kebayoran-square",
        title: "Kebayoran Square",
        priceStart: 4000000000,
        promo: "Promo Free PPN",
        category: "Commercial",
        bedrooms: 0,
        bathrooms: 2,
        location: "BSD City, Tangerang",
        status_sale: "For Rent",
    },
    {
        slug: "u-town-avenue",
        title: "U Town Avenue",
        priceStart: 4000000000,
        promo: "Promo Free PPN",
        category: "Commercial",
        bedrooms: 0,
        bathrooms: 2,
        location: "BSD City, Tangerang",
        status_sale: "For Rent",
    },
];
